[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "ds-test/=lib/forge-std/lib/ds-test/src/",
    "forge-std/=lib/forge-std/src/",
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "@oppenzeppelin-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/",
    "account-abstraction/=lib/account-abstraction/contracts/",
    "@4337/=lib/account-abstraction/contracts/",
    "@utils/=src/utils/",
    "@interfaces/=src/interfaces/",
    "@libraries/=src/libraries/",
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "openzeppelin-contracts/=lib/openzeppelin-contracts/",
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
fs_permissions = [{ access = "read-write", path = ".secret"}, { access ="read", path="./out/"}]
gas_reports = ["*"]
ffi = true 

solc = "0.8.20"
optimize = true
optimizer_runs = 100000
via_ir = true

[rpc_endpoints]
# INFURA_GOERLI_TEST_RPC_URL       = ""

[etherscan]
# mumbai = { key = "" }

[fmt]
line_length = 120
multiline_func_header = "params_first"
number_underscore="thousands"
# handle sorting of imports
